### PR TITLE
Frontend: Improve linter

### PR DESCRIPTION
**Pull request by Ludikrous**
Switch to eslint and lint-staged to fix the issue where lint fixes weren't automatically in the commit

### CODE REVIEW

**Comment by Ludikrous** [comment]
commit `d771dd1` is empty since the linter removed my error before commit got in

**Comment by burbelohugo** [comment]
@Ludikrous I'm getting a bunch of errors when I try to commit, can you let me know if I'm doing something wrong?

I pulled your branch, ran npm install, and made a few small edits to test what would be automatically fixed.

https://www.loom.com/share/9b7bebaec1c24a3e820b6d799bf155d6

**Comment by Ludikrous** [comment]
I think the initial lint will be long and might need some manual fixes, I'll do that later today

**Comment by burbelohugo** [comment]
Just let me know when this is ready for review, I'll hold off until you've added the fixes 👍

**Pull request merged**
